#!/bin/bash
# Phase 5: Deploy TOOLS.md and calendar-2026.json to VM workspace
# Run this on the VM after SCP'ing the files.
# SCP commands (from Windows PowerShell):
#   $sshKey = "C:\Users\henza\.ssh\id_rsa"
#   $vm = "henzard@<VM_IP>"
#   scp -i $sshKey docs/custom/vm-deploy/TOOLS.md "${vm}:~/.openclaw/workspace/TOOLS.md"
#   scp -i $sshKey docs/custom/vm-deploy/calendar-2026.json "${vm}:~/.openclaw/workspace/calendar-2026.json"

set -euo pipefail

WORKSPACE="$HOME/.openclaw/workspace"

echo "=== Phase 5: Setting up VM workspace files ==="

mkdir -p "$WORKSPACE"

# Verify TOOLS.md was SCP'd
if [ -f "$WORKSPACE/TOOLS.md" ]; then
    echo "--- TOOLS.md present ($(wc -l < "$WORKSPACE/TOOLS.md") lines) ---"
else
    echo "ERROR: TOOLS.md not found at $WORKSPACE/TOOLS.md"
    echo "SCP it first: scp -i ~/.ssh/id_rsa docs/custom/vm-deploy/TOOLS.md henzard@<VM_IP>:~/.openclaw/workspace/TOOLS.md"
    exit 1
fi

# Verify calendar-2026.json was SCP'd
if [ -f "$WORKSPACE/calendar-2026.json" ]; then
    echo "--- calendar-2026.json present ---"
else
    echo "ERROR: calendar-2026.json not found at $WORKSPACE/calendar-2026.json"
    exit 1
fi

# Ensure MEMORY.md exists and has the Do NOT edit header
if [ ! -f "$WORKSPACE/MEMORY.md" ]; then
    cat > "$WORKSPACE/MEMORY.md" <<'MEMEOF'
# Agent Memory

> Do NOT edit this file during Memory Synthesis or any automated cron. This file is human-maintained only.

## 2026 Goals

*Annual goals will be populated via guided WhatsApp session (Component 6).*

## Weekly Intentions

*Updated each Monday.*

## Notes

MEMEOF
    echo "--- MEMORY.md created ---"
else
    echo "--- MEMORY.md already exists ---"
fi

echo "=== Phase 5 complete ==="
